name: Weekly OTT Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 5" # Runs every Friday at 10:00 UTC (~3:30 PM IST)

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run OTT notification script
        env:
          STREAMING_API_KEY: ${{ secrets.STREAMING_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_ott_updates.py
